CREATE TABLE IF NOT EXISTS courses(
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    length INTEGER NOT NULL,
    url TEXT NOT NULL,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS authors(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    firstName TEXT NOT NULL,
    lastName TEXT NOT NULL,
    handle TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS grades(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    author_id INTEGER NOT NULL,
    course_id TEXT NOT NULL,
    grade INTEGER NOT NULL
);